# Generated by Django 5.0.3 on 2024-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTUApp', '0003_remove_authapimodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authapimodel',
            name='username',
        ),
        migrations.AddField(
            model_name='authapimodel',
            name='name',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authapimodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authapimodel',
            name='email',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='authapimodel',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
