# Generated by Django 5.0.3 on 2024-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTUApp', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authapimodel',
            name='phone_number',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
